In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Semi_cleaned_data2.csv')

In [4]:
traffic = {
'Low': 0,
'Medium': 1,
'High': 2,
'Jam': 3
}
Vehicle = {
'bicycle':0,
'scooter':1,
'motorcycle':2,
'electric_scooter':3
}

In [6]:
df['Road_traffic_density']=df['Road_traffic_density'].replace(traffic)
df['Type_of_vehicle']=df['Type_of_vehicle'].replace(Vehicle)

In [7]:
df.head()

,Delivery_person_ID,Delivery_person_Age,Delivery_person_Ratings,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),Distance in kms,Order_Day,Order_month,Order_year,Time_Orderd_Hour,Time_Orderd_mins,Time_Order_picked_Hour,Time_Order_picked_mins
0,12,36.0,4.2,Fog,3.0,2,Snack,2,3.0,No,Metropolitian,46,10.3,12,2,2022,21.0,55.0,22.0,10.0
1,13,21.0,4.7,Stormy,2.0,1,Meal,2,1.0,No,Metropolitian,23,6.2,13,2,2022,14.0,55.0,15.0,5.0
2,39,23.0,4.7,Sandstorms,1.0,1,Drinks,1,1.0,No,Metropolitian,21,13.8,4,3,2022,17.0,30.0,17.0,40.0
3,15,34.0,4.3,Sandstorms,0.0,0,Buffet,2,0.0,No,Metropolitian,20,2.9,13,2,2022,9.0,20.0,9.0,30.0
4,13,24.0,4.7,Fog,3.0,1,Snack,1,1.0,No,Metropolitian,41,19.4,14,2,2022,19.0,50.0,20.0,5.0

In [8]:
df.to_csv('Semi_cleaned_data3.csv')